# -*- coding: utf-8 -*-
"""Preprocess_External_Products_VisionAPI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U9JuH7tP9oMD4x2y52ClsMK_jGlyNTud
"""

!pip install google-cloud-vision

# 환경변수 설정
!ls /content/drive/'My Drive'/'Colab Notebooks'/'api'

import os
os.environ["GOOGLE_APPLICATION_CREDENTIALS"]="/content/drive/My Drive/Colab Notebooks/api/###############################.json"
!echo $GOOGLE_APPLICATION_CREDENTIALS # 체크

def detect_text(path):
    """Detects text in the file."""
    from google.cloud import vision
    import io
    client = vision.ImageAnnotatorClient()

    with io.open(path, 'rb') as image_file:
        content = image_file.read()

    image = vision.types.Image(content=content)

    response = client.text_detection(image=image)
    texts = response.text_annotations
    print('Texts:')

    for text in texts:
        print('\n"{}"'.format(text.description))

        vertices = (['({},{})'.format(vertex.x, vertex.y)
                    for vertex in text.bounding_poly.vertices])

        print('bounds: {}'.format(','.join(vertices)))

    if response.error.message:
        raise Exception(
            '{}\nFor more info on error messages, check: '
            'https://cloud.google.com/apis/design/errors'.format(
                response.error.message))
        
    return response, texts

test_image = '/content/drive/Shared drives/빅콘테스트/데이터(전처리 후 논의 대상)/이미지 테스트데이터/image6.jpg'